### ISSUE TITLE
디스크 캐시 구현

### ISSUE THREAD

**Issue by lina0322** [hcooch2ch3/ios-project-manager#12]

**Comment by lina0322** [comment]
❗️ 현재문제: 킬때마다 코어데이터에 정보가 모두 새로 저장되는 부분!!!

**Comment by lina0322** [comment]
클라이언트가 최신일 경우에 서버에 올려주는 부분도 고려해야함...........

**Comment by hcooch2ch3** [comment]
디스크 캐시 서버-클라이언트 동기화
1. 클라이언트가 최신인 경우
   - 클라이언트의 최신내역을 서버가 반영하도록 요청
2. 서버가 최신인 경우
   - 서버의 최신내역을 클라이언트가 반영하도록 요청
3. 클라이언트와 서버 둘다 최신일 경우
   - 서버가 클라이언트와 동일하다는 것을 알려주면 클라이언트는 디스크 캐시를 로드
